[package]
name = "visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.5"
yew = { version = "0.21.0", features = ["csr"] }
common = { path = "../common" }
wasm-bindgen-futures = "0.4"
