name: Post-Rust

on:
  workflow_dispatch:
    inputs: 
      run-id:
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  scrapper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: scrap-job-logs
      run: cargo run -p scrapper -- --run-id ${{ inputs.run-id }} 
                        --github-token ${{ secrets.GITHUB_TOKEN }} 
                        --owner PickDough 
                        --repo test-scrapper
