name: Post-Rust

on:
  workflow_dispatch:
    inputs: 
      run-id:
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  scrapper:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: scrap-job-logs
      run: cargo run -- --workflow-id ${{ inputs.run_id }} 
                        --github-token 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 
                        --owner PickDough 
                        --repo test-scrapper
