name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  output-1-and-3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: output-1-and-3
      run: cat ci/sample-outputs/output1.txt && cat ci/sample-outputs/output3.txt && fail-fail-fail
  output-2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: output-2
      run: cat ci/sample-outputs/output2.txt && fail-fail-fail
  call-post-rust:
    permissions: write-all
    if: always()
    needs:
    - output-2
    - output-1-and-3
    runs-on: ubuntu-latest

    steps:
      - name: curl
        run: curl -L 
                  -X POST 
                  -H "Accept:application/vnd.github+json"
                  -H "Authorization:Bearer ${{ secrets.GITHUB_TOKEN }} " 
                  -H "X-GitHub-Api-Version:2022-11-28" 
                  https://api.github.com/repos/PickDough/test-scrapper/actions/workflows/post-rust.yml/dispatches 
                  -d '{"ref":"${{ github.ref }}","inputs":{"run-id":"${{ github.run_id }}"}}'
    
