name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  output-1-and-3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: output-1-and-3
      run: cat ci/sample-outputs/output1.txt && cat ci/sample-outputs/output3.txt && fail-fail-fail
  output-2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: output-2
      run: cat ci/sample-outputs/output2.txt && fail-fail-fail
